datasets:
    15DL:
        paths: ['example-data-2.csv']
        fields: ['rsrp', 'rssi', 'rsrq', 'pdsch thp', 'bler']
        test: 'HTTP DL'
        altitude: 15

    15UL:
        paths: ['example-data-2.csv']
        fields: ['rsrp', 'rssi', 'rsrq', 'pusch thp', 'bler', 'tx pwr']
        test: 'HTTP UL'
        altitude: 15

graphs:
    RSRP_UL:
        datasets: ['1.5UL', '15UL', '30UL', '45UL']
        legends: ['1.5m', '15m', '30m', '45m']
        key: 'SS-SRSP'
        y-label: 'RSRP [dBm]'
        type: cdf
        size: (x, y)
        preview: True
        outdir: './../joku-kansio'

    RSSI_DL:
        datasets: ['1.5DL', '15DL', '30DL', '45m']
        legends: ['1.5m', '15m', '30m', '45m']
        key: 'SS-RSSI'
        y-label: 'RSSI [dB]'
        type: pdf
        size: (x, y)
        preview: True
        outdir: './../joku-kansio'
