db_file: db.json
es_url: 'http://localhost:9200/_bulk'
data_root: '/home/qubz/git/Parseri4000/example-data'

programs:
  qpoc:
    extension: 'csv'
    separator: ','
    root: 'qpoc'
    profiles:
      profile_a:
        subdir: 'sample_a'
        headers: ['SS-RSRP', 'SS-SINR', 'SS-RSRQ', 'Net PDSCH Thp (PCell)', 'BLER']
      profile_b: 
        subdir: 'sample_b'
        headers: ['SS-RSRP', 'SS-SINR', 'SS-RSRQ', 'Net PUSCH Thp', 'BLER', 'TxPower (PCell)']
